### ISSUE TITLE
What is Benchmark.exe binary?

### ISSUE THREAD

**Issue by matiit** [zettonaender/convtographiceq#1]
from Readme:
```Type 'Benchmark.exe -c 1 -f 1 -t 23000 -l 46 -r 48000 -o sweep.wav' (change 48000 to your sampling rate) (sweep.wav is an arbitrary filename)```

What is the Benchmark.exe binary? This file doesn't exist on Autoeq repository, it's not here either.

**Comment by wzhouiup** [comment]
Benchmark.exe is present in the EqualizerAPO install folder, default path for me being `C:\Program Files\EqualizerAPO`

**Comment by matiit** [comment]
Might be worth adding info about it to the readme

**Comment by matiit** [comment]
https://github.com/zettonaender/convtographiceq/pull/3

**Comment by zettonaender** [comment]
It's updated, thanks for the feedback!
