### ISSUE TITLE
Can the sweep.wav file be pregenerated and included in this repo? 

### ISSUE THREAD

**Issue by matiit** [zettonaender/convtographiceq#5]
Step:
```Type 'Benchmark.exe -c 1 -f 1 -t 23000 -l 46 -r 48000 -o sweep.wav' (change 48000 to your sampling rate) (sweep.wav is an arbitrary filename)```

Is the result file `sweep.wav` always the same for given parameters? Or is it dependent on the hardware of the user, like a sound card or something like this?

If this file is always the same for the given parameters - it could be pregenerated for various sampling rates and be included in this repo, it would save one step and simplify things.

**Comment by wzhouiup** [comment]
From my limited knowledge the sweep.wav should be a sine sweep up to 24khz for example for 48000 sampling rate. I am not sure if it takes into account the current EQ profile in Peace/equalizer apo as I have not been able to produce the intended curve in autoeq. I believe it should be specific for each user's EQ profile as that is what the graphic eq is being generated from

**Comment by matiit** [comment]
Ah, got it, if that takes the currently used curve in the equalizer apo then this definitely has to be provided by the user.

Makes sense, thanks
