### ISSUE TITLE
cannot import PREAMP_HEADROOM

### ISSUE THREAD

**Issue by wzhouiup** [zettonaender/convtographiceq#6]
When running the Autoeq command in Step 9, I get the error

`File "autoeq.py", line 9, in <module>
    from constants import DEFAULT_MAX_GAIN, DEFAULT_TREBLE_F_LOWER, DEFAULT_TREBLE_F_UPPER, DEFAULT_TREBLE_MAX_GAIN, \
ImportError: cannot import name 'PREAMP_HEADROOM' from 'constants' (C:\Users\Will\Desktop\AutoEq-master\constants.py)`

by including PREAMP_HEADROOM = 0.2 from the original constants.py the .csv file can be generated.

I believe this new constant is from the Nov. 20 commit in AutoEQ but the value of PREAMP_HEADROOM is not relevant right?

**Comment by wzhouiup** [comment]
This should just set the minimum headroom for the pre amp of a parametric EQ but I do not believe it pertains to the GraphicEQ file and is not used by Wavelet. Still, with the newer builds of AutoEQ this constant seems to be required?

**Comment by matiit** [comment]
It's definitely required.
And if autoeq will add any new constants there, they will be required to be changed in this project too, which is quite a inconvenience. 
It would be useful to know which parameters in constants file are changed and what for and then we could figure out a way to do it without needing a constants file at all (maybe a command line argument passed to the autoeq.py?)

**Comment by zettonaender** [comment]
Oh yeah, I think I used the file from an old AutoEq version.
I'll update the readme to note the changed values in a bit.
