### ISSUE TITLE
generated .csv and graphic eq results differ from Equalizer apo config

### ISSUE THREAD

**Issue by wzhouiup** [zettonaender/convtographiceq#7]
When generating the graphic eq file from the .csv the output does not match the intended curve in equalizer apo (peace)
![config](https://user-images.githubusercontent.com/28985448/110903165-e2c52c00-82bb-11eb-9a77-484668827440.png)
![Screenshot 2021-03-11 220949](https://user-images.githubusercontent.com/28985448/110903181-e8227680-82bb-11eb-9344-a9751d99d76f.png)

**Comment by zettonaender** [comment]
Can you try to generate a --Convolution_EQ on AutoEq and post the screenshot the Eq APO config screenshot as well? I'll take a look at it.

Edit: Sorry I was blind. Can you just post the 'expfloat.wav' file instead? Thanks a lot.

**Comment by zettonaender** [comment]
Also, what sample rate are you using for the benchmark.exe output?
Thanks.

**Comment by wzhouiup** [comment]
I ran the process again, and I included both the sweep.wav and the autoeq results in the zip.  My peace profile is also there.

[sweep.zip](https://github.com/zettonaender/convtographiceq/files/6132104/sweep.zip)

**Comment by zettonaender** [comment]
Alright thanks, I'll take a look.

**Comment by zettonaender** [comment]
Ah, dang. I forgot another step in the tutorial.  You need to add `; Benchmark` in the APO config.txt (or peace.txt) before running the benchmark tool. I updated the Readme to have this step (at step 4)

I did the EQ below. If you need a smoother graph you can change the smoothing in AutoEq constants. Although, the Graphic EQ itself is already smoothened by default.
Thanks for the report. Can I close this Issue?
[sweep.zip](https://github.com/zettonaender/convtographiceq/files/6133666/sweep.zip)

**Comment by wzhouiup** [comment]
It works as intended now, thanks!
