### ISSUE TITLE
Importlib install issue. 

### ISSUE THREAD

**Issue by cheeeebs** [zettonaender/convtographiceq#8]
Python version: 3.7 
Windows 10 Version 10.0.19041 Build 19041

When using pip install -r requirements.txt, CMD throws out ModuleNotFoundError: No module named 'importlib.util' at the end. I solved it by removing importlib from requirements.txt and installing it afterward, I don't know if this problem is reproducible.

**Comment by zettonaender** [comment]
Updated requirements.txt so importlib isn't required anymore.  It's not actually used with the final code so it's fine. Thanks for bringing this to my attention. Can you close this?
