### ISSUE TITLE
Messy oscillations in output

### ISSUE THREAD

**Issue by crimist** [zettonaender/convtographiceq#9]
Thanks for the great tool! I've been wanting a way to do this for a while.

## Issue

The first couple times I went through the process it was fine and my output pngs were smooth however after tweaking the EQ and re-exporting around 3 times I now get these very messy oscillations that shouldn't be there on the graph.

I've tried restarting my computer but the issue seems to persist. Even when trying other EQ files with different filters ect.

### Input
```
// device info ommited
Preamp: -4.5 dB
Filter: ON LS 24.2591 dB Fc 60 Hz Gain -0.5 dB
Filter: ON PK Fc 200 Hz Gain 3 dB Q 1.054
Filter: ON PK Fc 400 Hz Gain 0.4 dB Q 0.7959
Filter: ON PK Fc 950 Hz Gain -0.3 dB Q 1.0396
Filter: ON PK Fc 1600 Hz Gain 1.3 dB Q 3.6886
Filter: ON PK Fc 1900 Hz Gain 1 dB Q 3.6886
Filter: ON PK Fc 2100 Hz Gain -0.7 dB Q 4.3738
Filter: ON PK Fc 2900 Hz Gain 1.2 dB Q 9.1383
Filter: ON PK Fc 3000 Hz Gain 0.4 dB Q 26.4775
Filter: ON PK Fc 3100 Hz Gain -0.9 dB Q 1.3392
Filter: ON PK Fc 4000 Hz Gain 0.9 dB Q 8.8078
Filter: ON PK Fc 4300 Hz Gain 2.5 dB Q 5.9547
Filter: ON PK Fc 4600 Hz Gain 1 dB Q 10.886
Filter: ON PK Fc 5000 Hz Gain 2.5 dB Q 7.5312
Filter: ON PK Fc 5800 Hz Gain 3.8 dB Q 3.4903
Filter: ON PK Fc 7000 Hz Gain -0.7 dB Q 3.4903
Filter: ON PK Fc 8000 Hz Gain 0.3 dB Q 3.4903
Filter: ON HSC Fc 12000 Hz Gain 2 dB Q 0.918
Filter: ON HS Fc 15000 Hz Gain 1 dB
Filter: ON PK Fc 17000 Hz Gain -2 dB Q 8.1071
```

### Output

![ssweep](https://user-images.githubusercontent.com/20033376/114249122-8d2d7f00-994e-11eb-8a9b-a785be0d60a2.png)
[ssweep GraphicEQ.txt](https://github.com/zettonaender/convtographiceq/files/6288850/ssweep.GraphicEQ.txt)
[ssweep.csv](https://github.com/zettonaender/convtographiceq/files/6288856/ssweep.csv)

**Comment by crimist** [comment]
Interestingly if I remove the `; Benchmark` clause from the device line of the EQ I get this output:

![ssweep](https://user-images.githubusercontent.com/20033376/114249509-ad117280-994f-11eb-8d57-fe0fc42f6ccd.png)

I can't export my EQ than but it does seem to fix the jitter.

**Comment by zettonaender** [comment]
Apparently in eq apo, the peak gain is at 0.1 dB which causes clipping. This causes some issues and should be fixed by adding more negative preamp (peak gain -0.2 dB). I tried it with the GUI version and it fixes the oscillation mentioned. Can you try doing that?

**Comment by crimist** [comment]
Ah I thought I had enough preamp but clearly not:
![image](https://user-images.githubusercontent.com/20033376/114287249-60469e00-9a1a-11eb-8255-5da05b37b3a2.png)

That seems to fix it. Thanks!
![ssweep](https://user-images.githubusercontent.com/20033376/114287306-a0a61c00-9a1a-11eb-9140-45baf3f27333.png)
